spring.application.name=todos
server.port=8000

spring.datasource.url=jdbc:postgresql://localhost:5432/todos_db
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=${JWT_SECRET}
jwt.accessTokenExpiration=900000
jwt.refreshTokenExpiration=259200000